name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up nodejs for client
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Build client
        working-directory: ./client
        run: npm run build
        
  server-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up nodejs for client
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies for server
          working-directory: ./server
          run: npm install
        - name: Test Server
          working-directory: ./server
          run: npm run text
  classifier-server-build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
          python-version: "3.10"
     - name: Install Python dependencies
       working-directory: ./classifier_server
       run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
